# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170527_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
