# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170529_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
