# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_publication_perfil_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='perfil_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Perfil'),
        ),
    ]
